In [ ]:
import mysql.connector

import re

In [ ]:
mydb = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "rishivbps"
)
 
# Printing the connection object
print(mydb)

In [ ]:
cursor = mydb.cursor()
 
# Show database
cursor.execute("USE p1")

In [ ]:
cursor.execute("show tables")

In [ ]:
for x in cursor:
  print(x)

In [ ]:
from flask import Flask
from flask_graphql import GraphQLView
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

app.add_url_rule('/classrooms/', view_func=GraphQLView.as_view('graphql',
                 schema=schema, graphiql=True))
app.run(debug=True)

In [8]:
import sys

import graphene
import mysql.connector as mysql

class Domain(graphene.ObjectType):
    domainName = graphene.String()
    factTableName = graphene.String()

class College(graphene.ObjectType):
    name = graphene.String()
    url = graphene.String()
    publicOrPrivate = graphene.Int()
    region = graphene.Int()
    state = graphene.Int()
    focus = graphene.Int()
    setting = graphene.Int()
    collegeType = graphene.Int()
    collegeSize = graphene.Int()
    SATAvg = graphene.Int()
    collegeRanking = graphene.Int()
    sportsTradition = graphene.Int()
    studentFacultyRatio = graphene.Int()
    cost = graphene.Int()
    collegeAge = graphene.Int()
    
class Automobiles(graphene.ObjectType):
    autoID = graphene.String()
    url = graphene.String()
    usedOrNew = graphene.Int()
    bodyStyle = graphene.Int()
    make = graphene.Int()
    age = graphene.Int()
    priceRange = graphene.Int()
    sellerType = graphene.Int()
    mileage = graphene.Int()
    color = graphene.Int()
    sunroof = graphene.Int()
    luxurySeats = graphene.Int()
    transmission = graphene.Int()
    fuelType = graphene.Int()


class Queries(graphene.ObjectType):
    domain = graphene.List(Domain)
    college = graphene.List(College)
    automobiles = graphene.List(Automobiles)
    
    def resolve_domain(self, info):
        """ Connect to MySQL database """
        conn = None
        try:
            conn = mysql.connect(host='localhost',
                                           database='p1',
                                           user='root',
                                           password='rishivbps')
            if conn.is_connected():
                print('Connected to MySQL database')

        except Error as e:
            print(e)

        
        query = "select * from domain"
        cursor = db.cursor()
        cursor.execute(query)
        records = cursor.fetchall()
        cursor.close()
        db.close()
        #if len(records) == 0:
        #  return ??
        domain = []
        print(records)
        for record in records:
            domain.append(Domain(domainName=record[0],factTableName=record[1]))
        return domain
    
#schema=graphene.Schema(query=Queries)
#print(schema)

In [ ]:
def resolve_college(self,info,publicOrPrivate,region,state,focus,setting,collegeType,collegeSize,
                   SATAvg,collegeRanking,sportsTradition,studentFacultyRatio,cost,collegeAge):
    
        """ Connect to MySQL database """
        db = None
        try:
            db = mysql.connect(host='localhost',
                                           database='p1',
                                           user='root',
                                           password='rishivbps')
            if db.is_connected():
                print('Connected to MySQL database')

        except Error as e:
            print(e)
            
# SQL QUERY FORMATION
        query = "select * from collegeFactTable where "

        join_count=0
        
    #1: publicOrPrivate
        if 1 <= publicOrPrivate <= 3:
            if join_count>=1:
                squery=" and publicOrPrivate =  " + str(publicOrPrivate)
            else:
                squery="publicOrPrivate =  " + str(publicOrPrivate)
                join_count=1

            query=query+squery

    #2: region
        if len(region)!=0:
            region=re.sub("\s+", ",", region.strip())
            if join_count>=1:
                squery=" and region in (" + region +")"
            else:
                squery="region in (" + region +")"
                join_count=1
            
            query=query+squery
                
    #3: state multiselect
        if len(state)!=0:
            state=re.sub("\s+", ",", state.strip())
            if join_count>=1:
                squery=" and state in (" + state +")"
            else:
                squery="state in (" + state +")"
                join_count=1
                
            query=query+squery
    #4: focus
        if len(focus)!=0:
            focus=re.sub("\s+", ",", focus.strip())
            if join_count>=1:
                squery=" and focus in (" + focus +")"
            else:
                squery="focus in (" + focus +")"
                join_count=1
                
            query=query+squery
    
    #5: setting
        if len(setting)!=0:
            setting=re.sub("\s+", ",", setting.strip())
            if join_count>=1:
                squery=" and setting in (" + setting +")"
            else:
                squery="setting in (" + setting +")"
                join_count=1
                
    #6: collegeType
        if len(collegeType)!=0:
            collegeType=re.sub("\s+", ",", collegeType.strip())
            if join_count>=1:
                squery=" and collegeType in (" + collegeType +")"
            else:
                squery="collegeType in (" + collegeType +")"
                join_count=1
            query=query+squery
                
    #7: collegeSize
        if 1 <= collegeSize <= 3:    
            if join_count>=1:
                squery=" and collegeSize =  " + str(collegeSize)
            else:
                squery="collegeSize =  " + str(collegeSize)
                join_count=1
    #8 SATAvg
        if 1 <= SATAvg <= 5:
            if join_count>=1:
                squery=" and SATAvg =  " + str(SATAvg)
            else:
                squery="SATAvg =  " + str(SATAvg)
                join_count=1
                
            query=query+squery
    
    #9 collegeRanking
        if 1 <= collegeRanking <= 5:
            if join_count>=1:
                squery=" and collegeRanking =  " + str(collegeRanking)
            else:
                squery="collegeRanking =  " + str(collegeRanking)
                join_count=1
                
            query=query+squery
                
    #10: sportsTradition
        if 1 <= sportsTradition <= 3:
            if join_count>=1:
                squery=" and sportsTradition =  " + str(sportsTradition)
            else:
                squery="sportsTradition =  " + str(sportsTradition)
                join_count=1
                
            query=query+squery
            
    #11 studentFacultyRatio
        if 1 <= studentFacultyRatio <= 5:
            if join_count>=1:
                squery=" and studentFacultyRatio =  " + str(studentFacultyRatio)
            else:
                squery="studentFacultyRatio =  " + str(studentFacultyRatio)
                join_count=1
                
            query=query+squery
            
            
    #12: cost
        if 1 <= cost <= 5:
            if join_count>=1:
                squery=" and cost =  " + str(cost)
            else:
                squery="cost =  " + str(cost)
                join_count=1
            
            query=query+squery
            
    #13: collegeAge
        if 1 <= collegeAge <= 3:
            if join_count>=1:
                squery=" and collegeAge =  " + str(collegeAge)
            else:
                squery="collegeAge =  " + str(collegeAge)
                join_count=1
            query=query+squery
        
        cursor = db.cursor()
        cursor.execute(query)
        records = cursor.fetchall()
        cursor.close()
        db.close()
        
        college = []
        print(records)
        for record in records:
            college.append(Domain(domainName=record[0],factTableName=record[1]))
        return domain
                 



        
        if collegeAge
collegeRanking

collegeType
cost
focus
name

region
SATAvg
setting
sportsTradition
state
studentFacultyRatio
url

        
        
        cursor = db.cursor()
        cursor.execute(query)
        records = cursor.fetchall()
        cursor.close()
        db.close()
        
        
        
        
        
        
        #if len(records) == 0:
        #  return ??
        domain = []
        print(records)
        for record in records:
            domain.append(Domain(domainName=record[0],factTableName=record[1]))
        return domain

In [13]:
""" Connect to MySQL database """
conn = None
try:
        db = mysql.connect(host='localhost',
                                           database='p1',
                                           user='root',
                                           password='rishivbps')
        if db.is_connected():
                print('Connected to MySQL database')

except Error as e:
            print(e)

query1 = "use P1"
query = "select * from domain"

cursor = db.cursor()
cursor.execute(query)
records = cursor.fetchall()
print(records)

Connected to MySQL database
[('Automobiles', 'autoFactTable'), ('Colleges', 'collegeFactTable')]

In [15]:
studentFacultyRatio=1
query = "select * from collegeFactTable where "

if 1 <= studentFacultyRatio <= 5:
            squery="studentFacultyRatio = " + str(studentFacultyRatio)
            query=query+squery
print(query)

select * from collegeFactTable where studentFacultyRatio = 1

In [19]:
        db = None
        db = mysql.connect(host='localhost',
                                        database='p1',
                                        user='root',
                                        password='rishivbps')
        if db.is_connected():
            print('Connected to MySQL database')
            query = "select * from user where userid='Raj'"
            print(query)
            cursor = db.cursor()
            cursor.execute(query)
            records = cursor.fetchone()
            print(records[0])

Connected to MySQL database
select * from user where userid='Raj'
raj

In [30]:
import re
publicOrPrivate=1
region="1"
state="1 2"
focus=""
setting=""
collegeType=""
collegeSize=0
SATAvg=0
collegeRanking=0
sportsTradition=0
studentFacultyRatio=0
cost=0
collegeAge=0

In [35]:
# SQL QUERY FORMATION
query = "select * from collegeFactTable where "

join_count=0

#1: publicOrPrivate
if 1 <= publicOrPrivate <= 3:
    if join_count>=1:
        squery=" and publicOrPrivate = " + str(publicOrPrivate)
    else:
        squery="publicOrPrivate = " + str(publicOrPrivate)
        join_count=1

    query=query+squery

#2: region
if len(region)!=0:
    if len(region)==1:
        if join_count>=1:
            squery=" and region = " + region 
        else:
            squery="region = " + region 
            join_count=1
    else:
        region=re.sub("\s+", ",", region.strip())
        if join_count>=1:
            squery=" and region in (" + region +")"
        else:
            squery="region in (" + region +")"
            join_count=1

    query=query+squery

#3: state multiselect
if len(state)!=0:
    if len(state)==1:
        if join_count>=1:
            squery=" and state = " + state 
        else:
            squery="state = " + state 
            join_count=1
    else:
        state=re.sub("\s+", ",", state.strip())
        if join_count>=1:
            squery=" and state in (" + state +")"
        else:
            squery="state in (" + state +")"
            join_count=1

    query=query+squery
    
#4: focus
if len(focus)!=0:
    if len(focus)==1:
        if join_count>=1:
            squery=" and focus = " + focus 
        else:
            squery="focus = " + focus 
            join_count=1
    else:
        focus=re.sub("\s+", ",", focus.strip())
        if join_count>=1:
            squery=" and focus in (" + focus +")"
        else:
            squery="focus in (" + focus +")"
            join_count=1

    query=query+squery

#5: setting
if len(setting)!=0:
    if len(setting)==1:
        if join_count>=1:
            squery=" and setting = " + setting 
        else:
            squery="setting = " + setting 
            join_count=1
    else:
        setting=re.sub("\s+", ",", setting.strip())
        if join_count>=1:
            squery=" and setting in (" + setting +")"
        else:
            squery="setting in (" + setting +")"
            join_count=1

    query=query+squery

#6: collegeType
if len(collegeType)!=0:
    if len(collegeType)==1:
        if join_count>=1:
            squery=" and collegeType = " + collegeType 
        else:
            squery="collegeType = " + collegeType 
            join_count=1
    else:
        collegeType=re.sub("\s+", ",", collegeType.strip())
        if join_count>=1:
            squery=" and collegeType in (" + collegeType +")"
        else:
            squery="collegeType in (" + collegeType +")"
            join_count=1

    query=query+squery
    

#7: collegeSize
if 1 <= collegeSize <= 3:    
    if join_count>=1:
        squery=" and collegeSize =  " + str(collegeSize)
    else:
        squery="collegeSize =  " + str(collegeSize)
        join_count=1
        
#8 SATAvg
if 1 <= SATAvg <= 5:
    if join_count>=1:
        squery=" and SATAvg =  " + str(SATAvg)
    else:
        squery="SATAvg =  " + str(SATAvg)
        join_count=1

    query=query+squery

#9 collegeRanking
if 1 <= collegeRanking <= 5:
    if join_count>=1:
        squery=" and collegeRanking =  " + str(collegeRanking)
    else:
        squery="collegeRanking =  " + str(collegeRanking)
        join_count=1

    query=query+squery

#10: sportsTradition
if 1 <= sportsTradition <= 3:
    if join_count>=1:
        squery=" and sportsTradition =  " + str(sportsTradition)
    else:
        squery="sportsTradition =  " + str(sportsTradition)
        join_count=1

    query=query+squery

#11 studentFacultyRatio
if 1 <= studentFacultyRatio <= 5:
    if join_count>=1:
        squery=" and studentFacultyRatio =  " + str(studentFacultyRatio)
    else:
        squery="studentFacultyRatio =  " + str(studentFacultyRatio)
        join_count=1

    query=query+squery


#12: cost
if 1 <= cost <= 5:
    if join_count>=1:
        squery=" and cost =  " + str(cost)
    else:
        squery="cost =  " + str(cost)
        join_count=1

    query=query+squery

#13: collegeAge
if 1 <= collegeAge <= 3:
    if join_count>=1:
        squery=" and collegeAge =  " + str(collegeAge)
    else:
        squery="collegeAge =  " + str(collegeAge)
        join_count=1
    query=query+squery

In [36]:
query

'select * from collegeFactTable where publicOrPrivate = 1 and region = 1 and state in (1,2)'

In [ ]:
{
  college (publicOrPrivate: 1
  region: "1"
	state: ""
	focus: ""
	setting: ""
	collegeType: ""
	collegeSize: 0
	SATAvg: 0
	collegeRanking: 0
	sportsTradition: 0
	studentFacultyRatio: 0
	cost: 0
	collegeAge: 0){
    name
    url
    
  }
}

In [ ]:

# SQL QUERY FORMATION
query = "select * from autoFactTable where "

join_count=0

#1: usedOrNew
if len(usedOrNew)!=0:
    if len(usedOrNew)==1:
        if join_count>=1:
            squery=" and usedOrNew = " + usedOrNew 
        else:
            squery="usedOrNew = " + usedOrNew 
            join_count=1
    else:
        usedOrNew=re.sub("\s+", ",", usedOrNew.strip())
        if join_count>=1:
            squery=" and usedOrNew in (" + usedOrNew +")"
        else:
            squery="usedOrNew in (" + usedOrNew +")"
            join_count=1

    query=query+squery
    
#2: bodyStyle
if len(bodyStyle)!=0:
    if len(bodyStyle)==1:
        if join_count>=1:
            squery=" and bodyStyle = " + bodyStyle 
        else:
            squery="bodyStyle = " + bodyStyle 
            join_count=1
    else:
        collegeType=re.sub("\s+", ",", bodyStyle.strip())
        if join_count>=1:
            squery=" and bodyStyle in (" + bodyStyle +")"
        else:
            squery="bodyStyle in (" + bodyStyle +")"
            join_count=1

    query=query+squery
    


#3: make
if len(make)!=0:
    if len(make)==1:
        if join_count>=1:
            squery=" and make = " + make 
        else:
            squery="make = " + make 
            join_count=1
    else:
        make=re.sub("\s+", ",", make.strip())
        if join_count>=1:
            squery=" and make in (" + make +")"
        else:
            squery="make in (" + make +")"
            join_count=1

    query=query+squery
    
    
#4: age
if 1 <= age <= 4:
    if join_count>=1:
        squery=" and age =  " + str(age)
    else:
        squery="age =  " + str(age)
        join_count=1

    query=query+squery


#5: priceRange

if 1 <= priceRange <= 4:
    if join_count>=1:
        squery=" and priceRange =  " + str(priceRange)
    else:
        squery="priceRange =  " + str(priceRange)
        join_count=1

    query=query+squery

#6: sellerType

if 1 <= cost <= 2:
    if join_count>=1:
        squery=" and sellerType =  " + str(sellerType)
    else:
        squery="sellerType =  " + str(sellerType)
        join_count=1

    query=query+squery

#7: mileage

if 1 <= mileage <= 5:
    if join_count>=1:
        squery=" and cost =  " + str(mileage)
    else:
        squery="cost =  " + str(mileage)
        join_count=1

    query=query+squery
    

    
#8 color
if 1 <= color <= 16:
    if join_count>=1:
        squery=" and color =  " + str(color)
    else:
        squery="color =  " + str(color)
        join_count=1

    query=query+squery
    
    

#9: sunroof
if 1 <= sunroof <= 2:    
    if join_count>=1:
        squery=" and sunroof =  " + str(sunroof)
    else:
        squery="sunroof =  " + str(sunroof)
        join_count=1
        
#10 luxurySeats
if 1 <= luxurySeats <= 2:
    if join_count>=1:
        squery=" and luxurySeats =  " + str(luxurySeats)
    else:
        squery="luxurySeats =  " + str(luxurySeats)
        join_count=1

    query=query+squery

#11 transmission
if 1 <= transmission <= 2:
    if join_count>=1:
        squery=" and transmission =  " + str(transmission)
    else:
        squery="transmission =  " + str(transmission)
        join_count=1

    query=query+squery

#12: fuelType
if len(fuelType)!=0:
    if len(fuelType)==1:
        if join_count>=1:
            squery=" and fuelType = " + fuelType 
        else:
            squery="fuelType = " + fuelType 
            join_count=1
    else:
        fuelType=re.sub("\s+", ",", fuelType.strip())
        if join_count>=1:
            squery=" and fuelType in (" + fuelType +")"
        else:
            squery="fuelType in (" + fuelType +")"
            join_count=1

    query=query+squery

In [ ]:
def resolve_bookmarks(self,info,domain):
    """ Connect to MySQL database """
    db = None

    db = mysql.connect(host='localhost',
                                    database='p1',
                                    user='root',
                                    password='rishivbps')
    if db.is_connected():
        print('Connected to MySQL database')
        query = "SELECT property.propertyName, property.propertyquestion, property.propertyDisplayType, propertyDetail.allowedValue, propertyDetail.allowedValueCode FROM property INNER JOIN propertyDetail ON property.propertyName = propertyDetail.propertyName where property.domainName='{}' order by property.displayorder;".format(domain)
        print(query)
        cursor = db.cursor()
        cursor.execute(query)
        records = cursor.fetchall()
        print(records)
        cursor.close()
        db.close()
        ques=[]
        for record in records:
            ques.append(Ques(propertyName=record[0],propertyquestion=record[1],propertyDisplayType=record[2],allowedValue=record[3], allowedValueCode=record[4]))
        return ques

In [ ]:
SELECT p.domainName, p.displayorder, pd.propertyName, p.propertyQuestion, p.propertyDisplayType, JSON_ARRAYAGG(JSON_OBJECT('code', pd.allowedValueCode, 'value', pd.allowedValue)) AS 'options' FROM propertydetail AS pd  INNER JOIN property AS p ON p.propertyName=pd.propertyName WHERE p.domainName='{}' GROUP BY p.domainName, p.propertyName ORDER BY p.displayorder LIMIT 3 OFFSET {}